#!/usr/bin/env bash

set -e
[ -n "$MTENV_DEBUG" ] && set -x

mysql_PackageInstall()
{
	Downloadfile ${SQLTYPE}/${sql_dir}.tar.gz

	case "$SQLTODO" in
		1) # MYSQL 5.1.X && MariaDB 5.3.X
			./configure \
			--prefix=/mtimer/server/${SQLTYPE} \
			--localstatedir=/mtimer/server/${SQLTYPE}/data \
			--with-unix-socket-path=/mtimer/tmp/mysql.sock \
			--with-ssl=/usr/local/ssl \
			--sysconfdir=/etc \
			--with-mysqld-user=mysql \
			--with-charset=utf8 \
			--with-collation=utf8_general_ci \
			--with-extra-charsets=all \
			--enable-thread-safe-client \
			--with-big-tables \
			--with-embedded-server \
			--enable-local-infile \
			--enable-assembler \
			--with-plugins=innobase,partition \
			--with-mysqld-ldflags=-all-static \
			--with-client-ldflags=-all-static \
			--without-debug
			# --with-plugins=max-no-ndb
			;;
		2|3|5|6) # MYSQL 5.5.X, 5.6.X && MariaDB 5.5.X, 10.0.X
			cmake . \
			-DCMAKE_INSTALL_PREFIX=/mtimer/server/${SQLTYPE} \
			-DMYSQL_DATADIR=/mtimer/server/${SQLTYPE}/data \
			-DMYSQL_UNIX_ADDR=/mtimer/tmp/mysql.sock \
			-DWITH_SSL=/usr/local/ssl \
			-DSYSCONFDIR=/etc \
			-DWITH_EMBEDDED_SERVER=1 \
			-DCMAKE_BUILD_TYPE=Release \
			-DDEFAULT_CHARSET=utf8 \
			-DDEFAULT_COLLATION=utf8_general_ci \
			-DWITH_INNOBASE_STORAGE_ENGINE=1 \
			-DWITH_PARTITION_STORAGE_ENGINE=1 \
			-DWITH_READLINE=1 \
			-DENABLED_LOCAL_INFILE=1 \
			-DMYSQL_TCP_PORT=3306 \
			-DWITH_DEBUG=0
			#-DWITHOUT_TOKUDB=1 \ 因为需要大量 memory 或 swap
			#-DWITH_MYISAM_STORAGE_ENGINE=1 \
			#-DWITH_MEMORY_STORAGE_ENGINE=1 \
			#-DMYSQL_USER=mysql \
			;;
	esac

	make
	make install
}

mysql_Config()
{
	mv -f /etc/my.cnf /etc/my.cnf.old || true
	if [ "$SQLTODO" = "1" ];then
		cp -f ${MCONF_PATH}/${SQLTYPE}/my-old.cnf /etc/my.cnf

		ln -vs /mtimer/server/${SQLTYPE}/lib/mysql /usr/lib/mysql
		echo "/mtimer/server/$SQLTYPE/lib/mysql" >> /etc/ld.so.conf.d/mtenv_mysql.conf
	else
		cp -f ${MCONF_PATH}/${SQLTYPE}/my-new.cnf /etc/my.cnf

		ln -vs /mtimer/server/${SQLTYPE}/lib /usr/lib/mysql
		echo "/mtimer/server/$SQLTYPE/lib" >> /etc/ld.so.conf.d/mtenv_mysql.conf
	fi
	chown -R mysql /mtimer/server/${SQLTYPE}/
	chmod 755 ${MUNPACKED_PATH}/${sql_dir}/scripts/mysql_install_db
	${MUNPACKED_PATH}/${sql_dir}/scripts/mysql_install_db --basedir=/mtimer/server/${SQLTYPE} --datadir=/mtimer/server/${SQLTYPE}/data --user=mysql --defaults-file=/etc/my.cnf
	chown -R root:root /mtimer/server/${SQLTYPE}/
	chgrp -R mysql /mtimer/server/${SQLTYPE}/.
	chown -R mysql:mysql /mtimer/server/${SQLTYPE}/data/
	chown -R mysql:mysql /mtimer/log/${SQLTYPE}

	cp -f ${MINIT_PATH}/${DETECT_OS}/${SQLTYPE} /etc/init.d/mysql
	chmod 755 /etc/init.d/mysql

	ldconfig

	ln -vs /mtimer/server/${SQLTYPE}/include/mysql /usr/include/mysql
	#for i in /mtimer/server/${SQLTYPE}/bin/*; do ln -s $i /usr/bin/$2; done
	ln -s /mtimer/server/${SQLTYPE}/bin/* /usr/bin/

	DoInit add mysql
	#ln -s /etc/init.d/mysql /etc/rc3.d/S99mysql
	#ln -s /etc/init.d/mysql /etc/rc0.d/K01mysql

	service mysql start
}

mysql_Install()
{
	mysql_PackageInstall
	mysql_Config
}

command="$1"
case "$command" in
	"Install" | "Uninstall" | "Upgrade" )
		[ -z "$MTENV_V" ] && exec mtenv help mysql
		mysql_$command
		;;
	* )
		exec mtenv help mysql
		;;
esac