#!/usr/bin/env bash

set -e
[ -n "$MTENV_DEBUG" ] && set -x

ddos_ApfInstall()
{
	Downloadfile ddos/${apf_dir}.tar.gz
	./install.sh
	cp -f ${MCONF_PATH}/ddos/apf/conf.apf /etc/apf/conf.apf
	/usr/local/sbin/apf -s
}

ddos_BfdInstall()
{
	Downloadfile ddos/${bfd_dir}.tar.gz
	./install.sh

	# 是否发送邮件
	echo -ne "\nDo you want to send email alerts for all events ? [y/n] "
	while read EMAILALERT; do
		case "$EMAILALERT" in
			"y" | "Y" )
				sed -i 's/^EMAIL_ALERTS="0"/EMAIL_ALERTS="1"/' /usr/local/bfd/conf.bfd
				echo -ne "\nEnter your email address: "
				while read ALERTEMAIL; do
					export ALERTEMAIL
					case "$ALERTEMAIL" in
						"" ) echo -ne "\nIncorrect value option!\nPlease enter the correct value: " ;;
						* ) sed -i 's/^EMAIL_ADDRESS="root"/EMAIL_ADDRESS="$ALERTEMAIL"/' /usr/local/bfd/conf.bfd; break ;;
					esac
				done
				break ;;
			"n" | "N" ) break ;;
			*) echo -ne "\nIncorrect value option!\nPlease enter the correct value: " ;;
		esac
	done

	/usr/local/sbin/bfd -s
}

ddos_DeflateInstall()
{
	mkdir -p /usr/local/ddos/tmp
	
	Downloadfile ddos/${deflate_dir}.zip
	mv * /usr/local/ddos/

	cp -s /usr/local/ddos/ddos.sh /usr/local/sbin/ddos

	echo; echo -n 'Creating cron to run script every minute.....(Default setting)'
	/usr/local/ddos/ddos.sh --cron > /dev/null 2>&1

	echo; echo 'Installation has completed.'
	echo 'Config file is at /usr/local/ddos/ddos.conf'
	echo 'Please send in your comments and/or suggestions to zaf@vsnl.com'
	echo
	#cat /usr/local/ddos/LICENSE | less

	sed -i 's/^EMAIL_TO="root"/EMAIL_TO="$ALERTEMAIL"/' /usr/local/ddos/ddos.conf
	/usr/local/sbin/ddos -c
}

ddos_DeflateUninstall()
{
	echo; echo "Uninstalling DOS-Deflate"
	echo; echo; echo -n "Deleting script files....."
	if [ -e '/usr/local/sbin/ddos' ]; then
		rm -f /usr/local/sbin/ddos
		echo -n ".."
	fi
	if [ -d '/usr/local/ddos' ]; then
		rm -rf /usr/local/ddos
		echo -n ".."
	fi
	echo "done"
	echo; echo -n "Deleting cron job....."
	if [ -e '/etc/cron.d/ddos.cron' ]; then
		rm -f /etc/cron.d/ddos.cron
		echo -n ".."
	fi
	echo "done"
	echo; echo "Uninstall Complete"; echo
}

ddos_Install()
{
	ddos_ApfInstall
	ddos_BfdInstall
	ddos_DeflateUninstall
	ddos_DeflateInstall
}

command="$1"
case "$command" in
	"Install" | "DeflateUninstall" )
		[ -n "$MTENV_V" ] || exec mtenv help ddos
		ddos_$command
		;;
	* )
		exec mtenv help ddos
		;;
esac