#!/usr/bin/env bash

set -e
[ -n "$MTENV_DEBUG" ] && set -x

ubuntu_UpdateSource()
{
	cp -fp /etc/apt/sources.list /etc/apt/sources.list.back

	local os_release=$(grep -i "ubuntu" /etc/issue 2>/dev/null)
	if echo $os_release | grep -Eqi 'Ubuntu 10' >/dev/null 2>&1; then
		cat > /etc/apt/sources.list <<-EOF
		#ubuntu
		deb http://cn.archive.ubuntu.com/ubuntu/ maverick main restricted universe multiverse
		deb-src http://cn.archive.ubuntu.com/ubuntu/ maverick main restricted universe multiverse
		#ustc.edu.cn
		deb http://mirrors.ustc.edu.cn/ubuntu/ maverick main universe restricted multiverse
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ maverick main universe restricted multiverse
		deb http://mirrors.ustc.edu.cn/ubuntu/ maverick-updates universe main multiverse restricted
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ maverick-updates universe main multiverse restricted
		#lupaworld
		deb http://mirror.lupaworld.com/ubuntu/ maverick main universe restricted multiverse
		deb-src http://mirror.lupaworld.com/ubuntu/ maverick main universe restricted multiverse
		deb http://mirror.lupaworld.com/ubuntu/ maverick-security universe main multiverse restricted
		deb-src http://mirror.lupaworld.com/ubuntu/ maverick-security universe main multiverse restricted
		deb http://mirror.lupaworld.com/ubuntu/ maverick-updates universe main multiverse restricted
		deb http://mirror.lupaworld.com/ubuntu/ maverick-proposed universe main multiverse restricted
		deb-src http://mirror.lupaworld.com/ubuntu/ maverick-proposed universe main multiverse restricted
		deb http://mirror.lupaworld.com/ubuntu/ maverick-backports universe main multiverse restricted
		deb-src http://mirror.lupaworld.com/ubuntu/ maverick-backports universe main multiverse restricted
		deb-src http://mirror.lupaworld.com/ubuntu/ maverick-updates universe main multiverse restricted
		EOF
	elif echo $os_release | grep -Eqi 'Ubuntu 12' >/dev/null 2>&1; then
		cat > /etc/apt/sources.list <<-EOF
		#ubuntu
		deb http://cn.archive.ubuntu.com/ubuntu/ precise main restricted universe multiverse
		deb http://cn.archive.ubuntu.com/ubuntu/ precise-security main restricted universe multiverse
		deb http://cn.archive.ubuntu.com/ubuntu/ precise-updates main restricted universe multiverse
		deb http://cn.archive.ubuntu.com/ubuntu/ precise-proposed main restricted universe multiverse
		deb http://cn.archive.ubuntu.com/ubuntu/ precise-backports main restricted universe multiverse
		deb-src http://cn.archive.ubuntu.com/ubuntu/ precise main restricted universe multiverse
		deb-src http://cn.archive.ubuntu.com/ubuntu/ precise-security main restricted universe multiverse
		deb-src http://cn.archive.ubuntu.com/ubuntu/ precise-updates main restricted universe multiverse
		deb-src http://cn.archive.ubuntu.com/ubuntu/ precise-proposed main restricted universe multiverse
		deb-src http://cn.archive.ubuntu.com/ubuntu/ precise-backports main restricted universe multiverse
		#ustc.edu.cn
		deb http://mirrors.ustc.edu.cn/ubuntu/ precise main restricted
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ precise main restricted
		deb http://mirrors.ustc.edu.cn/ubuntu/ precise-updates main restricted
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ precise-updates main restricted
		deb http://mirrors.ustc.edu.cn/ubuntu/ precise universe
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ precise universe
		deb http://mirrors.ustc.edu.cn/ubuntu/ precise-updates universe
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ precise-updates universe
		deb http://mirrors.ustc.edu.cn/ubuntu/ precise multiverse
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ precise multiverse
		deb http://mirrors.ustc.edu.cn/ubuntu/ precise-updates multiverse
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ precise-updates multiverse
		deb http://mirrors.ustc.edu.cn/ubuntu/ precise-backports main restricted universe multiverse
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ precise-backports main restricted universe multiverse
		deb http://mirrors.ustc.edu.cn/ubuntu/ precise-security main restricted
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ precise-security main restricted
		deb http://mirrors.ustc.edu.cn/ubuntu/ precise-security universe
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ precise-security universe
		deb http://mirrors.ustc.edu.cn/ubuntu/ precise-security multiverse
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ precise-security multiverse
		deb http://extras.ubuntu.com/ubuntu precise main
		deb-src http://extras.ubuntu.com/ubuntu precise main
		#sohu
		deb http://mirrors.sohu.com/ubuntu/ precise main restricted
		deb-src http://mirrors.sohu.com/ubuntu/ precise main restricted
		deb http://mirrors.sohu.com/ubuntu/ precise-updates main restricted
		deb-src http://mirrors.sohu.com/ubuntu/ precise-updates main restricted
		deb http://mirrors.sohu.com/ubuntu/ precise universe
		deb-src http://mirrors.sohu.com/ubuntu/ precise universe
		deb http://mirrors.sohu.com/ubuntu/ precise-updates universe
		deb-src http://mirrors.sohu.com/ubuntu/ precise-updates universe
		deb http://mirrors.sohu.com/ubuntu/ precise multiverse
		deb-src http://mirrors.sohu.com/ubuntu/ precise multiverse
		deb http://mirrors.sohu.com/ubuntu/ precise-updates multiverse
		deb-src http://mirrors.sohu.com/ubuntu/ precise-updates multiverse
		deb http://mirrors.sohu.com/ubuntu/ precise-backports main restricted universe multiverse
		deb-src http://mirrors.sohu.com/ubuntu/ precise-backports main restricted universe multiverse
		deb http://mirrors.sohu.com/ubuntu/ precise-security main restricted
		deb-src http://mirrors.sohu.com/ubuntu/ precise-security main restricted
		deb http://mirrors.sohu.com/ubuntu/ precise-security universe
		deb-src http://mirrors.sohu.com/ubuntu/ precise-security universe
		deb http://mirrors.sohu.com/ubuntu/ precise-security multiverse
		deb-src http://mirrors.sohu.com/ubuntu/ precise-security multiverse
		deb http://extras.ubuntu.com/ubuntu precise main
		deb-src http://extras.ubuntu.com/ubuntu precise main
		#cn99
		deb http://ubuntu.cn99.com/ubuntu/ precise main restricted universe multiverse
		deb http://ubuntu.cn99.com/ubuntu/ precise-updates main restricted universe multiverse
		deb http://ubuntu.cn99.com/ubuntu/ precise-security main restricted universe multiverse
		deb http://ubuntu.cn99.com/ubuntu/ precise-backports main restricted universe multiverse
		#uestc
		deb http://ubuntu.uestc.edu.cn/ubuntu/ precise main restricted universe multiverse
		deb http://ubuntu.uestc.edu.cn/ubuntu/ precise-backports main restricted universe multiverse
		deb http://ubuntu.uestc.edu.cn/ubuntu/ precise-proposed main restricted universe multiverse
		deb http://ubuntu.uestc.edu.cn/ubuntu/ precise-security main restricted universe multiverse
		deb http://ubuntu.uestc.edu.cn/ubuntu/ precise-updates main restricted universe multiverse
		deb-src http://ubuntu.uestc.edu.cn/ubuntu/ precise main restricted universe multiverse
		deb-src http://ubuntu.uestc.edu.cn/ubuntu/ precise-backports main restricted universe multiverse
		deb-src http://ubuntu.uestc.edu.cn/ubuntu/ precise-proposed main restricted universe multiverse
		deb-src http://ubuntu.uestc.edu.cn/ubuntu/ precise-security main restricted universe multiverse
		deb-src http://ubuntu.uestc.edu.cn/ubuntu/ precise-updates main restricted universe multiverse
		#ustc
		deb http://debian.ustc.edu.cn/ubuntu/ precise main restricted universe multiverse
		deb http://debian.ustc.edu.cn/ubuntu/ precise-backports restricted universe multiverse
		deb http://debian.ustc.edu.cn/ubuntu/ precise-proposed main restricted universe multiverse
		deb http://debian.ustc.edu.cn/ubuntu/ precise-security main restricted universe multiverse
		deb http://debian.ustc.edu.cn/ubuntu/ precise-updates main restricted universe multiverse
		deb-src http://debian.ustc.edu.cn/ubuntu/ precise main restricted universe multiverse
		deb-src http://debian.ustc.edu.cn/ubuntu/ precise-backports main restricted universe multiverse
		deb-src http://debian.ustc.edu.cn/ubuntu/ precise-proposed main restricted universe multiverse
		deb-src http://debian.ustc.edu.cn/ubuntu/ precise-security main restricted universe multiverse
		deb-src http://debian.ustc.edu.cn/ubuntu/ precise-updates main restricted universe multiverse
		#bjtu
		deb http://mirror.bjtu.edu.cn/ubuntu/ precise main multiverse restricted universe
		deb http://mirror.bjtu.edu.cn/ubuntu/ precise-backports main multiverse restricted universe
		deb http://mirror.bjtu.edu.cn/ubuntu/ precise-proposed main multiverse restricted universe
		deb http://mirror.bjtu.edu.cn/ubuntu/ precise-security main multiverse restricted universe
		deb http://mirror.bjtu.edu.cn/ubuntu/ precise-updates main multiverse restricted universe
		deb-src http://mirror.bjtu.edu.cn/ubuntu/ precise main multiverse restricted universe
		deb-src http://mirror.bjtu.edu.cn/ubuntu/ precise-backports main multiverse restricted universe
		deb-src http://mirror.bjtu.edu.cn/ubuntu/ precise-proposed main multiverse restricted universe
		deb-src http://mirror.bjtu.edu.cn/ubuntu/ precise-security main multiverse restricted universe
		deb-src http://mirror.bjtu.edu.cn/ubuntu/ precise-updates main multiverse restricted universe
		#lupaworld
		deb http://mirror.lupaworld.com/ubuntu/ precise main universe restricted multiverse
		deb-src http://mirror.lupaworld.com/ubuntu/ precise main universe restricted multiverse
		deb http://mirror.lupaworld.com/ubuntu/ precise-security universe main multiverse restricted
		deb-src http://mirror.lupaworld.com/ubuntu/ precise-security universe main multiverse restricted
		deb http://mirror.lupaworld.com/ubuntu/ precise-updates universe main multiverse restricted
		deb http://mirror.lupaworld.com/ubuntu/ precise-proposed universe main multiverse restricted
		deb-src http://mirror.lupaworld.com/ubuntu/ precise-proposed universe main multiverse restricted
		deb http://mirror.lupaworld.com/ubuntu/ precise-backports universe main multiverse restricted
		deb-src http://mirror.lupaworld.com/ubuntu/ precise-backports universe main multiverse restricted
		deb-src http://mirror.lupaworld.com/ubuntu/ precise-updates universe main multiverse restricte
		EOF
	elif echo $os_release | grep -Eqi 'Ubuntu 14' >/dev/null 2>&1; then
		cat > /etc/apt/sources.list <<-EOF
		#ustc.edu.cn
		deb http://mirrors.ustc.edu.cn/ubuntu/ trusty main restricted universe multiverse
		deb http://mirrors.ustc.edu.cn/ubuntu/ trusty-security main restricted universe multiverse
		deb http://mirrors.ustc.edu.cn/ubuntu/ trusty-updates main restricted universe multiverse
		deb http://mirrors.ustc.edu.cn/ubuntu/ trusty-proposed main restricted universe multiverse
		deb http://mirrors.ustc.edu.cn/ubuntu/ trusty-backports main restricted universe multiverse
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ trusty main restricted universe multiverse
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ trusty-security main restricted universe multiverse
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ trusty-updates main restricted universe multiverse
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ trusty-proposed main restricted universe multiverse
		deb-src http://mirrors.ustc.edu.cn/ubuntu/ trusty-backports main restricted universe multiverse
		EOF
	fi

	apt-get update
}

ubuntu_TimeZone()
{
	# 设置时区
	rm -rf /etc/localtime
	ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
	apt-get install -y ntp ntpdate
	ntpdate -u pool.ntp.org
	date
	if [ ! $(grep -l 'disable monitor'    '/etc/ld.so.conf') ]; then
		echo 'disable monitor' >> /etc/ntp.conf
	fi
	service ntp restart
}
ubuntu_PreInstall()
{
	# 必要的准备
	vi_path=$(command -v vi)
	mv -f ${vi_path} ${vi_path}-old
	vim_path="$(command -v vim || true)"
	[ -n "$vim_path" ] || apt-get install -y vim
	ln -vs $(command -v vim) ${vi_path}
	if [ -s /etc/selinux/config ]; then
		sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
		setenforce 0 || true
	fi
}

ubuntu_Upgrade()
{
	apt-get install -y patch make autoconf2.13 gcc g++ flex file zlibc zlib1g zlib1g-dev zip libzip-dev unzip bzip2 libbz2-dev nano m4 perl libglib2.0-0 libglib2.0-dev libncurses5 libncurses5-dev libcap-dev xmlto sqlite libpam0g-dev libwrap0 libwrap0-dev libkrb5-dev db5.1-util logrotate quota libgd-graph-perl
	#xz-utils
}

ubuntu_EnvInstall()
{
	ubuntu_UpdateSource
	ubuntu_TimeZone
	ubuntu_PreInstall
	ubuntu_Upgrade

	apt-get install -y automake libtool libxml2 libxml2-dev tcl tk gettext e2fsprogs cpio expat
}

command="$1"
case "$command" in
	"EnvInstall" | "Upgrade" )
		[ -n "$MTENV_V" ] || exec mtenv help ubuntu
		ubuntu_$command
		;;
	* )
		exec mtenv help ubuntu
		;;
esac