#!/usr/bin/env bash

set -e
[ -n "$MTENV_DEBUG" ] && set -x

ddos_ApfInstall()
{
	Downloadfile ddos/${apf_dir}.tar.gz
	./install.sh
	cp -f ${MCONF_PATH}/ddos/apf/conf.apf /etc/apf/conf.apf
	/usr/local/sbin/apf -s > /dev/null 2>&1
}

ddos_BfdInstall()
{
	Downloadfile ddos/${bfd_dir}.tar.gz
	./install.sh

	# 是否发送邮件
	echo -ne "\nDo you want to send email alerts for all events ? [y/n] "
	while read EMAILALERT; do
		case "$EMAILALERT" in
			"y" | "Y" )
				sed -i 's/^EMAIL_ALERTS="0"/EMAIL_ALERTS="1"/' /usr/local/bfd/conf.bfd
				echo -ne "\nEnter your email address: "
				while read ALERTEMAIL; do
					export ALERTEMAIL
					case "$ALERTEMAIL" in
						"" ) echo -ne "\nIncorrect value option!\nPlease enter the correct value: " ;;
						* ) sed -i "s/^EMAIL_ADDRESS=\"root\"/EMAIL_ADDRESS=\"$ALERTEMAIL\"/" /usr/local/bfd/conf.bfd; break ;;
					esac
				done
				break ;;
			"n" | "N" ) break ;;
			*) echo -ne "\nIncorrect value option!\nPlease enter the correct value: " ;;
		esac
	done

	/usr/local/sbin/bfd -s > /dev/null 2>&1
	echo -e '\nBFD installed.'
}

ddos_ApfUninstall()
{
	echo "Removing apf and/or bfd if it exists..."
	echo

	if [ -d '/etc/apf' ]; then
		apf -f
		rm -fv /etc/cron.daily/fw
		rm -fv /etc/cron.daily/apf
		rm -fv /etc/cron.d/refresh.apf
		rm -fv /etc/logrotate.d/apf
		rm -fv /var/log/apf*
		DoInit remove apf
		rm -fv /etc/init.d/apf
		rm -Rfv /etc/apf

		rm -fv /etc/cron.d/bfd
		rm -fv /etc/logrotate.d/bfd
		rm -fv /var/log/bfd*
		rm -Rfv /usr/local/bfd
	fi

	echo
	echo "...Done"
}

ddos_CsfInstall()
{
	Downloadfile ddos/csf.tgz
	sh install.sh
	sh /usr/local/csf/bin/remove_apf_bfd.sh
	cp -f ${MCONF_PATH}/ddos/csf/csf.conf /etc/csf/csf.conf
	echo "# Run external commands before csf configures iptables" >> /usr/local/csf/bin/csfpre.sh
	echo "# Run external commands after csf configures iptables" >> /usr/local/csf/bin/csfpost.sh
	csf -x
}

ddos_CsfUninstall()
{
	if [ -d '/etc/csf' ]; then
		cd /etc/csf
		sh uninstall.sh
	fi
}

ddos_DeflateInstall()
{
	mkdir -p /usr/local/ddos/tmp
	
	Downloadfile ddos/${deflate_dir}.zip
	mv * /usr/local/ddos/
	chmod +x /usr/local/ddos/ddos.sh
	cp -s /usr/local/ddos/ddos.sh /usr/local/sbin/ddos

	echo -e '\nCreating cron to run script every minute.....(Default setting)'
	/usr/local/ddos/ddos.sh --cron > /dev/null 2>&1

	echo -e '\nDDos deflate installed.'
	echo 'Config file is at /usr/local/ddos/ddos.conf'
	echo
	#cat /usr/local/ddos/LICENSE | less

	sed -i "s/^EMAIL_TO=\"root\"/EMAIL_TO=\"$ALERTEMAIL\"/" /usr/local/ddos/ddos.conf
	/usr/local/sbin/ddos -c
}

ddos_DeflateUninstall()
{
	echo -e "\nUninstalling DOS-Deflate if it exists"
	if [ -e '/usr/local/sbin/ddos' ]; then
		rm -f /usr/local/sbin/ddos
	fi
	if [ -d '/usr/local/ddos' ]; then
		rm -rf /usr/local/ddos
	fi
	echo -e "\nDeleting cron job if it exists"
	if [ -e '/etc/cron.d/ddos.cron' ]; then
		rm -f /etc/cron.d/ddos.cron
	fi
	echo
}

ddos_Install()
{
	echo -ne "\nWhich firewall do you want to install? [1]Apf [2]Csf ?"
	while read WHICH; do
		case "$WHICH" in
			"1" ) 
				ddos_ApfInstall
				ddos_BfdInstall
				break ;;
			"2" ) 
				ddos_CsfInstall
				break ;;
			*) echo -ne "\nIncorrect value option!\nPlease enter the correct value: " ;;
		esac
	done

	ddos_DeflateUninstall
	ddos_DeflateInstall
}

ddos_Uninstall()
{
	ddos_ApfUninstall
	ddos_CsfUninstall
	ddos_DeflateUninstall
}

command="$1"
case "$command" in
	"Install" | "Uninstall" )
		[ -n "$MTENV_V" ] || exec mtenv help ddos
		ddos_$command
		;;
	* )
		exec mtenv help ddos
		;;
esac