#!/usr/bin/env bash

set -e
[ -n "$MTENV_DEBUG" ] && set -x

nginx_PackageInstall()
{
	unzip ${MEXTRA_PATH}/ngx-fancyindex-0.2.5-fixed.zip -d ${MUNPACKED_PATH}

	Downloadfile nginx/${nginx_dir}.tar.gz

	./configure --user=www --group=www --prefix=/mtimer/server/nginx --error-log-path=/mtimer/log/nginx/error.log --pid-path=/mtimer/tmp/nginx.pid --http-log-path=/mtimer/log/nginx/access.log --lock-path=/mtimer/tmp/nginx.lock --with-http_stub_status_module --without-http-cache --with-http_ssl_module --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_flv_module --http-client-body-temp-path=/mtimer/tmp/nginx/client --http-proxy-temp-path=/mtimer/tmp/nginx/proxy --http-fastcgi-temp-path=/mtimer/tmp/nginx/fcgi --http-uwsgi-temp-path=/mtimer/tmp/nginx/uwsgi --http-scgi-temp-path=/mtimer/tmp/nginx/scgi --add-module=${MUNPACKED_PATH}/ngx-fancyindex-0.2.5-fixed
	make
	make install
}

nginx_Config()
{
	cp -fR ${MCONF_PATH}/nginx/rewrite /mtimer/server/nginx/conf/
	cp -f ${MCONF_PATH}/nginx/nginx.conf /mtimer/server/nginx/conf/
	mkdir /mtimer/server/nginx/conf/vhosts
	cp -f ${MCONF_PATH}/nginx/vhosts/example.com.conf /mtimer/server/nginx/conf/vhosts/
	cp -f ${MCONF_PATH}/nginx/vhosts/soft.example.com.conf /mtimer/server/nginx/conf/vhosts/
	cp -f ${MCONF_PATH}/nginx/vhosts/${MSQLTYPE}.conf /mtimer/server/nginx/conf/vhosts/
	cp -f ${MCONF_PATH}/nginx/vhosts/dle.conf /mtimer/server/nginx/conf/vhosts/
	sed -i "s#www/dle#www/${dle_dir}#g" /mtimer/server/nginx/conf/vhosts/dle.example.com.conf
	sed -i "s#www/wordpress#www/${wp_dir}#g" /mtimer/server/nginx/conf/vhosts/wordpress.example.com.conf

	cp ${MEXTRA_PATH}/footer.html /mtimer/www/soft.example.com/

	chmod 755 /mtimer/server/nginx/sbin/nginx
	cp ${MINIT_PATH}/${DETECT_OS}/nginx /etc/init.d/nginx
	chmod +x /etc/init.d/nginx

	mkdir -p /mtimer/tmp/nginx/client
	DoInit add nginx
}

nginx_Install()
{
	nginx_PackageInstall
	nginx_Config
	service nginx start
}

command="$1"
case "$command" in
	"Install" | "Uninstall" | "Upgrade" )
		[ -z "$MTENV_V" ] && exec mtenv help nginx
		nginx_$command
		;;
	* )
		exec mtenv help nginx
		;;
esac